/********************************************************************
* dictsubeventalgo.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dictsubeventalgo.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictsubeventalgo();
extern void G__cpp_setup_inheritancedictsubeventalgo();
extern void G__cpp_setup_typetabledictsubeventalgo();
extern void G__cpp_setup_memvardictsubeventalgo();
extern void G__cpp_setup_globaldictsubeventalgo();
extern void G__cpp_setup_memfuncdictsubeventalgo();
extern void G__cpp_setup_funcdictsubeventalgo();
extern void G__set_cpp_environmentdictsubeventalgo();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SubEvent.hh"
#include "Flash.hh"
#include "SubEventList.hh"
#include "FlashList.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictsubeventalgoLN_TClass;
extern G__linked_taginfo G__dictsubeventalgoLN_TBuffer;
extern G__linked_taginfo G__dictsubeventalgoLN_TMemberInspector;
extern G__linked_taginfo G__dictsubeventalgoLN_TObject;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictsubeventalgoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictsubeventalgoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictsubeventalgoLN_subevent;
extern G__linked_taginfo G__dictsubeventalgoLN_subeventcLcLFlash;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlEsubeventcLcLFlashcOallocatorlEsubeventcLcLFlashgRsPgR;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlEsubeventcLcLFlashcOallocatorlEsubeventcLcLFlashgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictsubeventalgoLN_reverse_iteratorlEvectorlEsubeventcLcLFlashcOallocatorlEsubeventcLcLFlashgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictsubeventalgoLN_subeventcLcLFlashList;
extern G__linked_taginfo G__dictsubeventalgoLN_subeventcLcLFlashListcLcLSortMethod_t;
extern G__linked_taginfo G__dictsubeventalgoLN_subeventcLcLSubEvent;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlEsubeventcLcLSubEventcOallocatorlEsubeventcLcLSubEventgRsPgR;
extern G__linked_taginfo G__dictsubeventalgoLN_vectorlEsubeventcLcLSubEventcOallocatorlEsubeventcLcLSubEventgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictsubeventalgoLN_reverse_iteratorlEvectorlEsubeventcLcLSubEventcOallocatorlEsubeventcLcLSubEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictsubeventalgoLN_subeventcLcLSubEventList;
extern G__linked_taginfo G__dictsubeventalgoLN_subeventcLcLSubEventListcLcLSortMethod_t;

/* STUB derived class for protected member access */
typedef vector<subevent::Flash,allocator<subevent::Flash> > G__vectorlEsubeventcLcLFlashcOallocatorlEsubeventcLcLFlashgRsPgR;
typedef vector<subevent::SubEvent,allocator<subevent::SubEvent> > G__vectorlEsubeventcLcLSubEventcOallocatorlEsubeventcLcLSubEventgRsPgR;
