////////////////////////////////////////////////////////////////////////
// Class:       UBT0Finder
// Module Type: producer
// File:        UBT0Finder_module.cc
//
// Generated at Tue Sep 13 22:21:49 2016 by Kazuhiro Terao using artmod
// from cetpkgsupport v1_10_02.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include <memory>

class UBT0Finder;

class UBT0Finder : public art::EDProducer {
public:
  explicit UBT0Finder(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  UBT0Finder(UBT0Finder const &) = delete;
  UBT0Finder(UBT0Finder &&) = delete;
  UBT0Finder & operator = (UBT0Finder const &) = delete;
  UBT0Finder & operator = (UBT0Finder &&) = delete;

  // Required functions.
  void produce(art::Event & e) override;


private:

  // Declare member data here.

};


UBT0Finder::UBT0Finder(fhicl::ParameterSet const & p)
// :
// Initialize member data here.
{
  // Call appropriate produces<>() functions here.
}

void UBT0Finder::produce(art::Event & e)
{
  // Implementation of required member function here.
}

DEFINE_ART_MODULE(UBT0Finder)
